### ISSUE TITLE
Documentation on MacroContent

### ISSUE THREAD

**Issue by madman2021** [Mountain-BC/DisplayPad.SDK.Demo#3]
Any documentation on how to use MacroContent in the SDK
```csharp
 public struct MacroInputContent_DisplayPad
    {
      public int iSrc;
      public int iType;
      public int iTimes;
      public int iEventLen;
      [MarshalAs((UnmanagedType) 30, SizeConst = 1000, ArraySubType = (UnmanagedType) 27)]
      public DisplayPadSDK.KEYMAP_EVENT[] pData;
    }
```

**Comment by madman2021** [comment]
Can't find anything that describes what iType, iSrc do

**Comment by madman2021** [comment]
Looking at creating a replacement program to manage the keys and what they do, essentially a replacement for Base Camp with more features and a better Icon generator utilizing font awesome for icons etc.

Would the SDK allow me to achieve that ?

**Comment by ravi-devitpl** [comment]
> Can't find anything that describes what iType, iSrc do

We have added a document for your reference in the repo, please check.
"MacroInputContent_DisplayPad" struct is used to save the Macro in hardware if you are using or configuring the device in the hardware mode. Otherwise, you can set up the macro in software mode is by utilizing the key event and send the key press signal to OS.
[Macro.docx](https://github.com/Mountain-BC/DisplayPad.SDK.Demo/files/12912354/Macro.docx)

**Comment by ravi-devitpl** [comment]
> he SDK allow me to achieve that ?

Yes, you can utilize the key events to customize the keys and what they do on the key press. There are 2 methods available to upload the images in hardware, **UploadImage** is to upload the image in software mode (the image will not be saved in hardware) and **UploadImageBySetIconPic** for the hardware mode.

**Comment by ravi-devitpl** [comment]
Marking it as Close
